---
#
# Ansible managed
#
repository:
  description: Install and configure logwatch on your system.
  homepage: https://robertdebock.nl/
  topics: logwatch, monitoring, ansible, molecule, tox, playbook
