---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "wAxN3jgQcZ2KFO9QsYCuZ3onDqmmHMOUClf0anconlh26MFTbY5SmQZ90fTu1MiNhDUdiKmH4SK7QKHO5x4qAcDKtY+2L5JcoNVmvaAjfO2WLsV4B35hyuGHVoVc3A5Joh2mnFg2DToT2s4XtMJCKg6+H5jFNYI9MgqMhFmOE7ta3q2I9HzBsm8PhCxI2xzC2e5IUQ/JeMOEnuIfDcADjlwC3gDdG/g6nmxnexemq2vERVOGqBcgy92MUhp//nRC5nZ6EsRYud8MfNJc1gNf+DV0aWwutvuG983gsnz+QlnqzNHbV2tThMZNA+9vBvl4aHX4CkAAtBg4PDJaMgnsTovLU8BvHawgMtbjuvQbddveMGeBdM4wSv9fpIOQuK41GH3Pm52b6Lh1owNsU2e5PEdbOqIQ8yflVPjqwjifDNXxbH/5lOliGyryCLdt4gd4gy4puHZXi0vQVapNMHl2ucsNifTBj7esG1O3Kna5W7n7VbEoFD0LE3ESSohJU+raBCsABEpdRxTOfn9eeWy6gXeNM/m0j+Bq2VlXRMPRPrOdIAm/2/hdxGDS99CiCHeTSKOHTPqZJ6YgOhg+YnkeYN3KZTG8Zs3TvMrlqygZwqJ5XYqXU2U8k9XDkYlN2SL57lT3HBXwBu/rhtHpbYL9X45r+A+yP5Jlhx2ZgAbbxnE="
  email: false
