---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    # - namespace="archlinux/" image="base"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - image="docker-opensuse-systemd"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "UUlcHCLFL7MpqbfklBCiWeygcdju6wDytyqjgAVTPTwJpVGLfhI2CXN+98AwYcMldttJtNrQxmCSGsquI2LHU6WzYjBoPNcAFzUUOEkpNcK9YIxUhvbDEZDL/aORbLBRM05zYuRzvVWWUIx57kp/oc1wj+9A4Q7McCk+i/t7VaGiHG5arAqwxtB5mFUOpEzFmR4r242keKk/YGifhKX8zLngH5OYAC9Jz2DFrr2pCrQpSba235byXEPDAo+OStfOsfyvZjp5C49X39eTx9QIcxzScFkLe2tGTqyVuEUwrz2Hf9ycZWWfhpmKanUqNEfL2RIbpWEa7XVxzM3CbWZcOk3isTyRu8lcEMhHCIuJQqyH01ZFoc0Bi29c19e407hOLXA1jH0xIc7TMJDolhuNYNttXv1TEo83+5eXU0K1LYIy3BhEoiPCMb7DRYf1TJITuC//TUqVCkwiv2dkz6A/4ym7sUpPvViPpINmsEsNHiJutfua2B1VgoxNWuuNEK4JECXGRWt5DRjnsOd2gh2+G25106mOy47Ptdwnv/eqqd44g+A3+J+2BtiV5u43Ug6QSp9s6f3b/aEousztqUeKEPhLSUNkg67RlRjj4Az3r/SKDhrB4tPH9nrduoTv2Zr5WY8DNsi98ycCzQc4dcQfLydbIwnYFwHEiQRbFJJsUAw="
  email: false
